<?php
error_reporting(E_ALL^E_NOTICE); //this function tell the error mechanisms
require 'dbConnect.php';

$extension='';
$files_array = array();


/* Opening the thumbnail directory and looping through all the thumbs: */

$dir_handle = @opendir($directory) or die("There is an error with your file directory!"); //this function open the dirtectory path..and read the content and become file handler...search on google for more detail... :)
while ($file = readdir($dir_handle)) 
{
	/* Skipping the system files: */
	if($file{0}=='.') continue;  // escape "htaccess" file --it is used for modify permission on web server..
	
	/* end() returns the last element of the array generated by the explode() function: */
	$parts = explode('.',$file);// the explode function divide the second parameter and first parameter define from where to divide..
	$extension = strtolower(end($parts));
	
	/* Skipping the php files: */
	if($extension == 'php') continue;

	$files_array[]=$file;
}

/* Sorting the files alphabetically */
sort($files_array,SORT_STRING);

$file_downloads=array();

$result = mysql_query("SELECT * FROM `downloadmanager`");

if(mysql_num_rows($result))
while($row=mysql_fetch_assoc($result))
{
	//mysql_fetch_assoc will convert the result in associative array which contain key and value type format..
	//	The "key" of the $file_downloads array will be the name of the file, and will contain the number of downloads: 
	
		
	$file_downloads[$row['filename']]=$row['downloads'];
}




?>







<!DOCTYPE html>
<html>
<head>
<script type="text/javascript" src="jquery.js"></script>
<script type="text/javascript">
	$(document).ready(function(){
	/* This code is executed after the DOM has been completely loaded */

	$('a').click(function(){
		
		var countSpan = $('.download-count',this);
		countSpan.text( parseInt(countSpan.text())+1); //this function take string type and return first encounter interger in the string only....
	});
});
</script>
<link rel="stylesheet" type="text/css" href="milligram.css">
	<title> download counter</title>
</head>
<body>
	
<div class="container">
<div class="row">
<div class="column">


</div>
</div></div>

<div class="container">
<div class="row">
<div class="column">
<h3 style="text-align:center;">Download Counter</h3>
</div>
</div></div>

<div class="container" >
<div class="row">
<div class="column column-20">
space here.....
</div>
<div class="column column-50" style="border:1px solid red; height:30em;overflow-y: scroll;overflow-x: hidden;;">
<div class="row">
<div class="column">
<h4 style="text-align:center;">file manager</h4>
</div></div>

<?php

foreach ($files_array as $key => $val) {
echo '<div class="row" id="fileColumn" > 
<div class="column" style="border:1px solid blue;">
<a href="download.php?file='.urlencode($val).'">'.$val.'<span class="download-count" style="padding-left:5rem">'.(int)$file_downloads[$val].'</span>
<span id="download-lable" style="float:right;padding-right:2rem;">download</span>
</a>
</div>
</div> ';}

// urlencode:- this function convert all non-alphanumeric such space into %20 and so on.. into url specific format to parse data..





?>
</div>
<div class="column column-20">
spce here....
</div>
</div></div>
</body>
</html>